version: '3.4'

services:
  app:
    build: . # locate dockerfile
    volumes:
      - .:/opt/app # shared folder
      - yarn-cache:/opt/.yarn-cache # cache
    ports:
      - '8888:8888' # port mirror

volumes:
    yarn-cache:
