version: '3.4'

services:
    app:
        build: . # locate dockerfile
        volumes:
        - .:/opt/app # shared folder
        - yarn-cache:/opt/.yarn-cache # cache
        ports:
        - '8888:8888' # port mirror
        environment:
            DB_TABLE_PREFIX: '' # options for qa/staging/production
            PORT: '8888'

    dynamodb:
        image: deangiberson/aws-dynamodb-local

volumes:
    yarn-cache:
