version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
            name: Test
            command: yarn test --ci --testResultsProcessor="jest-junit"
            environment:
                JEST_JUNIT_OUTPUT: "test-result/Jest/js-test-results.xml"

      - store_test_results:
        ath: test-results

      - run:
          name: Build
          command: yarn clean && yarn build
